[project]
name = 'Blockchain-Based-Financial-Regulatory-Compliance'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.compliance-requirements]
path = 'contracts/compliance-requirements.clar'
clarity_version = 2
epoch = 2.5

[contracts.institution-verification]
path = 'contracts/institution-verification.clar'
clarity_version = 2
epoch = 2.5

[contracts.monitoring-protocol]
path = 'contracts/monitoring-protocol.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
